name: Velostrada
favicon: null
layout_spectrum: 0.43659
typography_spectrum: 0.25603
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.9775622205343097
  lightness: 0.9175207747612149
  saturation: 0.9508165202569216
  rhythmicContrast: 0.32772451592609286
purpose: []
